#!/bin/tcsh -f

# CMSC 216, Spring 2023, Project #9
# Public test 4 (public04)
#
# Runs yargs.x in three ways that should not cause any output to be
# produced (this time without the -n option):
#
#   - The first time it is run with no target program (therefore no target
#     arguments either), and no standard input
#
#   - The second time it is run with a target program, but no target
#     arguments and no standard input
#
#   - The third time it is run with a target program, and some target
#     arguments, but no standard input
#
# In all three cases the -n option is not used. and yargs.x should have an
# exit status of zero in all three cases.
#
# If you want to debug your code for the first execution below, run
# gdb yargs.x.  Then (perhaps after setting some breakpoints), in gdb, use
# the command:
#
#   run < public01+04.inputdata
#
# If you want to debug your code for the second execution below, run
# gdb yargs.x.  Then (perhaps after setting some breakpoints), in gdb, use
# the command:
#
#   run /bin/echo < public01+04.inputdata
#
# If you want to debug your code for the first execution below, run
# gdb yargs.x.  Then (perhaps after setting some breakpoints), in gdb, use
# the command:
#
#   run make -f nonexistent-makefile < public01+04.inputdata
#
# (c) Larry Herman, 2023.  You are allowed to use this code yourself, but
# not to provide it to anyone else.

# all three runs use an empty input file 

echo "The first run:"
./yargs.x < public01+04.inputdata
if ($status != 0) then
  # error exit
  echo "Problem!  yargs.x did not exit with status 0 in the first run."
  exit 9
endif

echo "The second run:"
# "/bin/echo" is the target program name
./yargs.x /bin/echo < public01+04.inputdata
if ($status != 0) then
  # error exit
  echo "Problem!  yargs.x did not exit with status 0 in the second run."
  exit 9
endif

echo "The third run:"
# "make" is the target program name and "-f" and "nonexistent-makefile" are
# the two target arguments
./yargs.x make -f nonexistent-makefile < public01+04.inputdata
if ($status != 0) then
  # error exit
  echo "Problem!  yargs.x did not exit with status 0 in the third run."
  exit 9
endif
