#!/bin/tcsh -f

# CMSC 216, Spring 2023, Project #9
# Public test 5 (public05)
#
# Runs yargs.x with /bin/echo as the target program, with one line of data
# in its standard input; /bin/echo will be called on the line so will print
# it.
#
# If you want to debug your code for this test, run gdb yargs.x.  Then
# (perhaps after setting some breakpoints), in gdb, use the command:
#
#   run /bin/echo < public05.inputdata
#
# (c) Larry Herman, 2023.  You are allowed to use this code yourself, but
# not to provide it to anyone else.

# an empty input file
./yargs.x /bin/echo < public05.inputdata

if ($status != 0) then
  # error exit
  echo "Problem!  yargs.x did not exit with status 0."
  exit 9
endif
