#!/bin/tcsh -f

# CMSC 216, Spring 2023, Project #9
# Public test 11 (public11)
#
# Runs yargs.x to test its exit status for successful invocations of the
# target program (it should exit with status 0 when every invocation of the
# target program had exit status 0).
#
# If you want to debug your code for this test, run gdb yargs.x.  Then
# (perhaps after setting some breakpoints), in gdb, use the command:
#
#   run ls < public11.inputdata
#
# (c) Larry Herman, 2023.  You are allowed to use this code yourself, but
# not to provide it to anyone else.

# Note we are not even examining the output that is produced (">& /dev/null
# throws it away); in this test we are only concerned with the exit status
# of yargs.x.  Note that the exit status of ls is 0 if all files given on
# its command line exist and can be listed.
./yargs.x ls < public11.inputdata >& /dev/null

if (!($status)) then
  # normal exit
  echo "Success!  yargs.x exited with status 0 when the target program did."
  exit 0
else
  # error exit
  echo "Problem!  yargs.x did not exit with status 0 even though the target"
  echo "program did."
  exit 9
endif
